DROP TABLE IF EXISTS types;
CREATE TABLE types (
  TYPE_ID       BIGINT(20)   NOT NULL AUTO_INCREMENT,
  TYPE          VARCHAR(100) NOT NULL,
  AUDIT_VERSION BIGINT(20),
  ARCHIVED      CHAR(1),
  CREATED_BY    BIGINT(20),
  DATE_CREATED  DATETIME,
  DATE_UPDATED  DATETIME,
  UPDATED_BY    BIGINT(20),
  PRIMARY KEY (TYPE_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;